### ISSUE TITLE
Issues from old repository

### ISSUE THREAD

**Issue by wil93** [algorithm-ninja/cmsocial#20]
- [ ] veluca93/oii-web#5
- [ ] veluca93/oii-web#19
- [ ] veluca93/oii-web#29
- [ ] veluca93/oii-web#30
